use_frameworks!

target 'RSFontSizes_Example' do
  platform :ios, '12.0'
  pod 'RSFontSizes', :path => '../'

  target 'RSFontSizes_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0.0'
    pod 'Nimble', '~> 8.0.1'
  end
  
  post_install do |lib|
    lib.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
  
end
