use_frameworks!

target 'RSFontSizes_Example' do
  pod 'RSFontSizes', :path => '../'

  target 'RSFontSizes_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0.0'
    pod 'Nimble', '~> 8.0.1'
  end
end
